[package]
name = "ofclicker"
version = "0.1.0"
authors = ["John Peel <john@dgby.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
rocket_contrib = "0.4.5"
pickledb = "0.4.1"
